RepositorioUABC/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    
    path('',include('home.urls'))
    
]

home/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index, name='Index'),
    path('autores/', views.autores, name='autores'),
    path('contenido/',views.contenido, name='contenido'),
    path('contenido/<int:id>', views.visualizar, name='visualizar'),
    path('contenido/agregar', views.agregar, name="agregar"),
    path('validacion/', views.validacion, name='validacion'),
    path('clear-session/', views.clear_session, name='clear_session')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class ContentType(models.Model):
    name = models.CharField(max_length=124)
    def __str__(self):
        return self.name

class Repository(models.Model):
    name = models.CharField(max_length=124)
    location = models.CharField(max_length=124)

    def __str__(self):
        return self.name

class Area(models.Model):
    name = models.CharField(max_length=124)

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=124)
    last_name = models.CharField(max_length=124)

class Item(models.Model):
    title = models.CharField(max_length=200)
    year = models.IntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    authors = models.ManyToManyField(Author, through='AuthorItem')
    pdf = models.FileField(upload_to='pdfs/', null=True, blank=True)

class AuthorItem(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

home/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.forms import BaseInlineFormSet
from .models import Item, AuthorItem

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title', 'year', 'area', 'repository', 'content_type', 'pdf']

    def clean(self):
        cleaned_data = super().clean()
        pdf = cleaned_data.get('pdf')

        if not pdf:
            raise forms.ValidationError("Porfavor suba un archivo pdf.")

        if pdf and not pdf.name.endswith('.pdf'):
            raise forms.ValidationError("Solo se admiten archivos pdf.")

        return cleaned_data
    
class AuthorItemForm(forms.ModelForm):
    first_name = forms.CharField(max_length=124, required=True)
    last_name = forms.CharField(max_length=124, required=True)

    class Meta:
        model = AuthorItem
        fields = ['first_name', 'last_name']

class BaseAuthorItemFormSet(BaseInlineFormSet):
    def clean(self):
        super().clean()
        if any(self.errors):
            return

        has_author = False
        for form in self.forms:
            if form.cleaned_data and not form.cleaned_data.get('DELETE', False):
                has_author = True
                break

        if not has_author:
            raise forms.ValidationError("Debe agregar al menos un autor.")

AuthorItemFormSet = inlineformset_factory(
    Item, AuthorItem, form=AuthorItemForm, formset=BaseAuthorItemFormSet, extra=2, can_delete=True
)

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse
from .models import Author, Item, AuthorItem
from django.db.models import Q, Count
from .forms import ItemForm, AuthorItemFormSet
from pdf2image import convert_from_path
import os
from django.conf import settings

# Create your views here.
def index(request):
    content_types = Item.objects.values('content_type_id', 'content_type__name').annotate(num_items=Count('id'))
    areas = Item.objects.values('area_id', 'area__name').annotate(num_items=Count('id'))
    repositories = Item.objects.values('repository_id', 'repository__name').annotate(num_items=Count('id'))
    year_production = Item.objects.values('year').annotate(recursos=Count('year'))
    last_added = Item.objects.all().order_by('-id').values()[:50]
    authors = Author.objects.all()
    
    context = {
        'content_types': content_types,
        'areas': areas,
        'repositories': repositories,
        'year_production': year_production,
        'last_added': last_added,
        'authors' : authors
    }

    return render(request, 'index.html', context)

def autores(request):
    letter = request.GET.get('letter', '')
    authors = Author.objects.filter(first_name__istartswith=letter)
    authors = authors.distinct().annotate(item_count=Count('authoritem__item')).order_by('first_name', 'last_name')

    context = {
        'authors': authors,
        'letter': letter,
    }

    return render(request, 'autores.html', context)

def generate_pdf_thumbnail(pdf_path, thumbnail_path):
    pages = convert_from_path(pdf_path, 60, poppler_path=r'C:\Program Files\poppler-24.07.0\Library\bin')
    page = pages[0]
    page.save(thumbnail_path, 'JPEG')

def contenido (request):
    search = request.GET.get('search', '')
    year = request.GET.get('year', '')
    content_type = request.GET.get('content_type', '')
    area = request.GET.get('area', '')
    repository = request.GET.get('repository', '')
    page_number = request.GET.get('page', 1)
    author_id = request.GET.get('author_id', '')

    items = Item.objects.all().prefetch_related('authors')

    if search:
        search_terms = search.split()
        if len(search_terms) == 2:
            first_name, last_name = search_terms
            items = items.filter(
                Q(title__icontains=search) |
                Q(authors__first_name__icontains=first_name) &
                Q(authors__last_name__icontains=last_name)
            ).distinct()
        else:
            items = items.filter(
                Q(title__icontains=search) |
                Q(authors__first_name__icontains=search) |
                Q(authors__last_name__icontains=search)
            ).distinct()

    if year:
        items = items.filter(year=year)

    if content_type:
        items = items.filter(content_type=content_type)

    if area:
        items = items.filter(area=area)
    
    if repository:
        items = items.filter(repository=repository)

    if author_id:
        items = items.filter(authors__id=author_id).distinct()

    paginator = Paginator(items, 12)
    page_obj = paginator.get_page(page_number)


    content_types = Item.objects.values('content_type_id', 'content_type__name').annotate(num_items=Count('id'))
    areas = Item.objects.values('area_id', 'area__name').annotate(num_items=Count('id'))
    repositories = Item.objects.values('repository_id', 'repository__name').annotate(num_items=Count('id'))
    year_production = Item.objects.values('year').annotate(recursos=Count('year'))
    last_added = Item.objects.all().order_by('-id').values()[:50]
    authors = Author.objects.all()
    
    context = {
        'items': page_obj,
        'content_types': content_types,
        'areas': areas,
        'repositories': repositories,
        'year_production': year_production,
        'last_added': last_added,
        'author_id': author_id,
        'search': search,
        'year': year,
        'content_type': content_type,
        'area': area,
        'repository': repository,
        'paginator': paginator,
        'page_obj': page_obj,
        'authors': authors
    }

    return render(request, 'contenido.html', context)

def visualizar(request, id):
    item = Item.objects.get(pk=id)
    authors = item.authors.all()
    return render(request, 'visualizar.html', {'item': item, 'authors': authors})

def agregar(request):
    if not request.session.get('has_access'):
        return redirect('validacion')

    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        formset = AuthorItemFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            try:
                item = form.save()
                pdf = request.FILES['pdf']
                pdf_path = os.path.join(settings.MEDIA_ROOT, item.pdf.name)
                
                for author_form in formset:
                    if author_form.cleaned_data:
                        first_name = author_form.cleaned_data.get('first_name')
                        last_name = author_form.cleaned_data.get('last_name')
                        if first_name and last_name:
                            author, created = Author.objects.get_or_create(
                                first_name=first_name,
                                last_name=last_name
                            )
                            AuthorItem.objects.create(author=author, item=item)
                
                thumbnail_path = os.path.join(settings.MEDIA_ROOT, f'thumbnails/{item.id}.jpg')
                generate_pdf_thumbnail(pdf_path, thumbnail_path)

                messages.success(request, 'La obra fue subida exitosamente!')
                form = ItemForm()
                formset = AuthorItemFormSet()
            except Exception as e:
                messages.error(request, f'Error: {str(e)}')
    else:
        form = ItemForm()
        formset = AuthorItemFormSet()

    return render(request, 'agregar.html', {'form': form, 'formset': formset})

def validacion(request):
    if request.method == 'POST':
        key = request.POST.get('key')
        if key == '1234':  # Remplaza '1234' con una clave segura
            request.session['has_access'] = True
            return redirect('agregar')
        else:
            return HttpResponse('Clave invalida', status=403)

    return render(request, 'validacion.html')

def clear_session(request):
    request.session['has_access'] = False
    return redirect('enter_key')

home/templates/agregar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <style>
      #home {
        background-image: url("{% static 'images/UABC.jpeg' %}");
      }
    </style>
    <title>Agregar archivo | Repositorio UABC</title>
  </head>
  <body>
    <header>
      <nav>
        <a href="/" class="nav-left">
          <img class="logo" src="{% static 'images/uabc-logo.png' %}" alt="logo de UABC" />
          <span>Repositorio de Cuerpo Académico FCA</span>
        </a>
        <ul class="menuList">
          <li class="menuList-item">
            <a href="{% url 'Index' %}">Inicio</a>
          </li>
          <li class="menuList-item">
            <a href="{% url 'contenido' %}">Catálogo</a>
          </li>
        </ul>
        <div class="nav-mobile">
          <input
            hidden=""
            class="check-icon"
            id="check-icon"
            name="check-icon"
            type="checkbox"
          />
          <label class="icon-menu" for="check-icon">
            <div class="bar bar--1"></div>
            <div class="bar bar--2"></div>
            <div class="bar bar--3"></div>
          </label>
        </div>
      </nav>
    </header>
    <main id="form" class="bg-img-container">
        <div class="items-form">
          <h4>Agregar una obra</h4>
            {% if messages %}
                <ul>
                {% for message in messages %}
                    <li{% if message.tags %} class="successlist"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <form id="item-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-item">
                  <h6 for="id_title">Título:</h6>
                  {{ form.title }}
                </div>
                <div class="form-item">
                  <h6 for="id_year">Año:</h6>
                  {{ form.year }}
                </div>
                <div class="form-item">
                  <h6 for="id_area">Área:</h6>
                  {{ form.area }}
                </div>
                <div class="form-item">
                  <h6 for="id_repository">Repositorio:</h6>
                  {{ form.repository }}
                </div>
                <div class="form-item">
                  <h6 for="id_content_type">Tipo de Contenido:</h6>
                  {{ form.content_type }}
                </div>
                <div class="form-item">
                  <h6 for="id_pdf">PDF:</h6>
                  {{ form.pdf }}
                </div>
              <h6>Autores</h6>
              <div id="author-formset">
                  {{ formset.management_form }}
                  {% for form in formset %}
                      <div class="author-form">
                        <p>
                          <label for="id_authoritem_set-{{ forloop.counter0 }}-first_name">Nombre:</label>
                          {{ form.first_name }}
                      </p>
                      <p>
                          <label for="id_authoritem_set-{{ forloop.counter0 }}-last_name">Apellido:</label>
                          {{ form.last_name }}
                          {{ form.id }}
                          {{ form.item }}
                      </p>
                      </div>
                  {% endfor %}
              </div>
              <button class="form-btn" type="button" id="add-author">Agregar otro autor</button>
              <button style="float: right; margin-top: 16px;" class="secondary-btn" type="submit">Agregar Obra</button>
            </form>
        </div>
    </main>
    <footer>
      <div class="footer-content">
        <div class="top-footer">
          <span>Nuestras Redes Sociales</span>
        </div>
        <nav class="bottom-footer">
          <a target="_blank" href="https://www.facebook.com/fcatijuana/">
            <i class="bx bxl-facebook-circle"></i>
          </a>
          <a
            target="_blank"
            href="https://www.instagram.com/fca.tij.uabc/?igshid=YmMyMTA2M2Y%3D"
          >
            <i class="bx bxl-instagram"></i>
          </a>
          <a
            target="_blank"
            href="https://www.tiktok.com/@fca.tij?_t=8UYWhCdbMPN&_r=1"
          >
            <i class="bx bxl-tiktok"></i>
          </a>
          <a target="_blank" href="https://www.youtube.com/c/FCATijuana">
            <i class="bx bxl-youtube"></i>
          </a>
          <a target="_blank" href="https://www.linkedin.com/in/fcatijuana/">
            <i class="bx bxl-linkedin"></i>
          </a>
        </nav>
      </div>
    </footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
          const formset = document.getElementById('author-formset');
          const addAuthorButton = document.getElementById('add-author');
          const totalForms = document.getElementById('id_authoritem_set-TOTAL_FORMS');

          addAuthorButton.addEventListener('click', function() {
              const formCount = parseInt(totalForms.value);
              
              const newFormHTML = `
                  <div class="author-form">
                      <p>
                          <label for="id_authoritem_set-${formCount}-first_name">Nombre:</label>
                          <input type="text" name="authoritem_set-${formCount}-first_name" maxlength="124" id="id_authoritem_set-${formCount}-first_name">
                      </p>
                      <p>
                          <label for="id_authoritem_set-${formCount}-last_name">Apellido:</label>
                          <input type="text" name="authoritem_set-${formCount}-last_name" maxlength="124" id="id_authoritem_set-${formCount}-last_name">
                          <input type="hidden" name="authoritem_set-${formCount}-id" id="id_authoritem_set-${formCount}-id">
                          <input type="hidden" name="authoritem_set-${formCount}-item" id="id_authoritem_set-${formCount}-item">
                      </p>
                  </div>
              `;
              
              formset.insertAdjacentHTML('beforeend', newFormHTML);
              
              totalForms.value = formCount + 1;
          });
      });
    </script>

    <style>
      .form-item {
        margin-bottom: 12px;
      }

      .form-item input,  .form-item select{
        width: 100%;
      }

      #author-formset {
        max-height: 200px;
        overflow-y: scroll;
      }
      .author-form {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 10px;
      }

      .author-form p {
        display: flex;
        flex-direction: column;
        text-align: center;
      }

      .form-btn {
        background: var(--primary-color);
        color: #fff;
        padding-inline: 8px;
        padding-block: 4px;
        border-radius: 4px;
        cursor: pointer;
        font-weight: 600;
        font-size: 12px;
        transition: background 400ms ease;
      }
    </style>
</html>

home/templates/autores.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <style>
      #home {
        background-image: url("{% static 'images/UABC.jpeg' %}");
      }
    </style>
    <title>Inicio | Repositorio UABC</title>
  </head>
  <body>
    <header>
      <nav>
        <a href="/" class="nav-left">
          <img class="logo" src="{% static 'images/uabc-logo.png' %}" alt="logo de UABC" />
          <span>Repositorio de Cuerpo Académico FCA</span>
        </a>
        <ul class="menuList">
          <li class="menuList-item">
            <a href="{% url 'Index' %}">Inicio</a>
          </li>
          <li class="menuList-item">
            <a href="{% url 'contenido' %}">Catálogo</a>
          </li>
        </ul>
        <div class="nav-mobile">
          <input
            hidden=""
            class="check-icon"
            id="check-icon"
            name="check-icon"
            type="checkbox"
          />
          <label class="icon-menu" for="check-icon">
            <div class="bar bar--1"></div>
            <div class="bar bar--2"></div>
            <div class="bar bar--3"></div>
          </label>
        </div>
      </nav>
    </header>
    <main id="authors">
        <h2>Autores</h2>
        <div class="letter-navigation">
            {% for char in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
                <a href="?letter={{ char }}" class="{% if letter == char %}active{% endif %}">{{ char }}</a>
            {% endfor %}
                <a href="?">
                  <svg fill="#000000" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
                    width="14px" height="14px" viewBox="0 0 485 485" xml:space="preserve">
                  <g>
                    <g>
                      <rect x="67.224" width="350.535" height="71.81"/>
                      <path d="M417.776,92.829H67.237V485h350.537V92.829H417.776z M165.402,431.447h-28.362V146.383h28.362V431.447z M256.689,431.447
                        h-28.363V146.383h28.363V431.447z M347.97,431.447h-28.361V146.383h28.361V431.447z"/>
                    </g>
                  </g>
                  </svg>
                </a>
        </div>

        <div class="author-list">
            {% if authors %}
                <ul>
                    {% for author in authors %}
                        <li>
                            <a class="link" href="/contenido/?author_id={{ author.id }}">{{ author.first_name }} {{ author.last_name }} ({{ author.item_count }})</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
            <div class="notFound">
              <p>No se encontro ningun autor.</p>
            </div>
            {% endif %}
        </div>
    </main>
    <footer>
      <div class="footer-content">
        <div class="top-footer">
          <span>Nuestras Redes Sociales</span>
        </div>
        <nav class="bottom-footer">
          <a target="_blank" href="https://www.facebook.com/fcatijuana/">
            <i class="bx bxl-facebook-circle"></i>
          </a>
          <a
            target="_blank"
            href="https://www.instagram.com/fca.tij.uabc/?igshid=YmMyMTA2M2Y%3D"
          >
            <i class="bx bxl-instagram"></i>
          </a>
          <a
            target="_blank"
            href="https://www.tiktok.com/@fca.tij?_t=8UYWhCdbMPN&_r=1"
          >
            <i class="bx bxl-tiktok"></i>
          </a>
          <a target="_blank" href="https://www.youtube.com/c/FCATijuana">
            <i class="bx bxl-youtube"></i>
          </a>
          <a target="_blank" href="https://www.linkedin.com/in/fcatijuana/">
            <i class="bx bxl-linkedin"></i>
          </a>
        </nav>
        <a class="btn" href="{% url 'agregar' %}">
          <span class="btn-content"></span>
        </a>
      </div>
    </footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
      href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <style>
      #home {
        background-image: url("{% static 'images/UABC.jpeg' %}");
      }
    </style>
    <title>Inicio | Repositorio UABC</title>
  </head>
  <body>
    <header>
      <nav>
        <a href="/" class="nav-left">
          <img class="logo" src="{% static 'images/uabc-logo.png' %}" alt="logo de UABC" />
          <span>Repositorio de Cuerpo Académico FCA</span>
        </a>
        <ul class="menuList">
          <li class="menuList-item">
            <a href="{% url 'Index' %}">Inicio</a>
          </li>
          <li class="menuList-item">
            <a href="{% url 'contenido' %}">Catálogo</a>
          </li>
        </ul>
        <div class="nav-mobile">
          <input
            hidden=""
            class="check-icon"
            id="check-icon"
            name="check-icon"
            type="checkbox"
          />
          <label class="icon-menu" for="check-icon">
            <div class="bar bar--1"></div>
            <div class="bar bar--2"></div>
            <div class="bar bar--3"></div>
          </label>
        </div>
      </nav>
    </header>
    <main>
      <section class="bg-img-container">
        <div class="home-container">
          <div class="home-content">
            <div class="home-info">
              <h1>Explora el Repositorio Digital FCA</h1>
              <p>
                Explora nuestro gran catálogo de libros de nuestra institución.
              </p>
            </div>
            <form class="search-form" method="GET" action="{% url 'contenido' %}">
              {% csrf_token %}
              <div class="group">
                <svg class="icon" aria-hidden="true" viewBox="0 0 24 24">
                  <g>
                    <path
                      d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"
                    ></path>
                  </g>
                </svg>
                <input name="search" placeholder="Buscar por profesor o titulo de la obra." type="search" class="input" value="{{ search }}"/>
              </div>
              <button class="btn" type="submit">Buscar</button>
            </form>
          </div>
        </div>
      </section>
      <section id="contents">
        <div class="contents-header">
          <h2>Índice de contenidos</h2>
        </div>
        <div class="contents-cards">
          <!----------------- YEAR OF PRODUCTION ----------------->
          <article class="card">
            <h5>Año de Producción</h5>
            <ul>
              {% for item in year_production %}
              <li>
                <a href="/contenido/?year={{ item.year }}">{{ item.year }}</a>
                <span>Recursos: {{item.recursos}}</span>
              </li>
              {% endfor %}
            </ul>
          </article>
          <!----------------- TYPE OF CONTENT ----------------->
          <article class="card">
            <h5>Tipo de contenido</h5>
            <ul>
              {% for item in content_types %}
              <li>
                <a href="/contenido/?content_type={{ item.content_type_id }}">{{ item.content_type__name }}</a>
                <span>Recursos: {{item.num_items}}</span>
              </li>
              {% endfor %}
            </ul>
          </article>
          <!----------------- AREA ----------------->
          <article class="card">
            <h5>Área</h5>
            <ul>
              {% for item in areas %}
              <li>
                <a href="/contenido/?area={{ item.area_id }}">{{ item.area__name }}</a>
                <span>Recursos: {{item.num_items}}</span>
              </li>
              {% endfor %}
            </ul>
          </article>
          <!----------------- REPOSITORIES ----------------->
          <article class="card">
            <h5>Repositorio</h5>
            <ul>
              {% for item in repositories %}
              <li>
                <a href="/contenido/?repository={{ item.repository_id }}">{{ item.repository__name }}</a>
                <span>Recursos: {{ item.num_items }}</span>
              </li>
              {% endfor %}
            </ul>
          </article>
          <!----------------- LAST ADDED ----------------->
          <article class="card">
            <h5>Últimos Agregados</h5>
            <ul>
              {% for item in last_added %}
              <li>
                <a href="/contenido/{{item.id}}">{{ item.title }}</a>
              </li>
              {% endfor %}
            </ul>
          </article>
          <!----------------- Authors ----------------->
          <article class="card">
            <a class="link" href="{% url 'autores' %}">
              <h5>Autores</h5>
            </a>
            <ul>
              {% for author in authors %}
              <li>
                <a href="/contenido/?author_id={{ author.id }}">{{ author.first_name }} {{ author.last_name }}</a>
              </li>
              {% endfor %}
            </ul>
          </article>
        </div>
      </section>
    </main>
    <footer>
      <div class="footer-content">
        <div class="top-footer">
          <span>Nuestras Redes Sociales</span>
        </div>
        <nav class="bottom-footer">
          <a target="_blank" href="https://www.facebook.com/fcatijuana/">
            <i class="bx bxl-facebook-circle"></i>
          </a>
          <a
            target="_blank"
            href="https://www.instagram.com/fca.tij.uabc/?igshid=YmMyMTA2M2Y%3D"
          >
            <i class="bx bxl-instagram"></i>
          </a>
          <a
            target="_blank"
            href="https://www.tiktok.com/@fca.tij?_t=8UYWhCdbMPN&_r=1"
          >
            <i class="bx bxl-tiktok"></i>
          </a>
          <a target="_blank" href="https://www.youtube.com/c/FCATijuana">
            <i class="bx bxl-youtube"></i>
          </a>
          <a target="_blank" href="https://www.linkedin.com/in/fcatijuana/">
            <i class="bx bxl-linkedin"></i>
          </a>
        </nav>
        <a class="btn" href="{% url 'agregar' %}">
          <span class="btn-content"></span>
        </a>
      </div>
    </footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>